#BASE_URL
#BASE.URL=http://localhost:8080

#Local
#spring.datasource.url=jdbc:postgresql://localhost:5432/flyflix
#spring.datasource.username=admin
#spring.datasource.password=123
#spring.datasource.driver-class-name=org.postgresql.Driver
org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# === BASE URL ===
BASE.URL=https://flyflix.onrender.com
spring.config.encoding=UTF-8
spring.jpa.open-in-view=false
frontend.url=https://flyrecursos.vercel.app
frontend.login-path=/login



# === ConexÃ£o principal - PostgreSQL (Render) ===

spring.datasource.url=jdbc:postgresql://dpg-d3lanemmcj7s739pp790-a.oregon-postgres.render.com/flyflixdb_cb76
spring.datasource.username=flyflix_user
spring.datasource.password=YID89cdXxo3XcgjDi8kBSlEgG6qIYivy
spring.datasource.driver-class-name=org.postgresql.Driver





# === ConfiguraÃ§Ãµes bÃ¡sicas JPA ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



# === Porta do servidor (Render define via variÃ¡vel de ambiente) ===
server.port=${PORT:8080}

# === Flyway (desativado por enquanto) ===
spring.flyway.enabled=false

# === InicializaÃ§Ã£o de dados ===
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# === CORS ===
app.cors.allowed-origins=https://flyflix.onrender.com,http://localhost:3000,http://127.0.0.1:5173

# === PaginaÃ§Ã£o e ordenaÃ§Ã£o ===
spring.data.web.pageable.page-parameter=pagina
spring.data.web.pageable.size-parameter=tamanho
spring.data.web.sort.sort-parameter=ordem

# === ConfiguraÃ§Ã£o do servidor SMTP do Gmail ===
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=atendimento@flyeducacao.org
spring.mail.password=tjoupdfoaahqtgdp
spring.mail.protocol=smtp
spring.mail.default-encoding=UTF-8

# SMTP Propriedades
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

#Upload de arquivos
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB





# === RSA JWT ===
jwt.public.key=classpath:app.pub
jwt.private.key=classpath:app.key

# === Logging (nÃ­vel detalhado apenas se necessÃ¡rio) ===
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.org.springdoc=INFO
#logging.level.org.springframework.security=INFO
#logging.level.org.springframework.security.web.access=INFO
#logging.level.org.springframework.security.authentication=INFO
#logging.level.org.springframework.security.oauth2=INFO

# === Stacktrace ===
server.error.include-stacktrace=never
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot=DEBUG
logging.level.root=DEBUG




