# ======================================
# 🌐 CONFIGURAÇÕES GERAIS
# ======================================

server.port=${PORT:8080}

spring.config.encoding=UTF-8
spring.jpa.open-in-view=false
org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.flyway.enabled=false
spring.jpa.hibernate.ddl-auto=update



# URL base da API e do frontend
# application-dev.properties
BASE.URL=http://localhost:8080
#BASE.URL=https://flyflix.onrender.com
frontend.url=https://flyrecursos.vercel.app
frontend.login-path=/login


# ======================================
# 🗄️  CONEXÃO COM BANCO DE DADOS (Render)
# ======================================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false




# ======================================
# 🔐 JWT CONFIG
# ======================================

# Tempo de expiração do Access Token (em minutos)
jwt.expiration-minutes=15

# Tempo de expiração do Refresh Token (em dias)
jwt.refresh-expiration-days=7



jwt.private.key=classpath:app.key
jwt.public.key=classpath:app.pub






#Local
#spring.datasource.url=jdbc:postgresql://localhost:5432/flyflix
#spring.datasource.username=admin
#spring.datasource.password=123
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=atendimento@flyeducacao.org
spring.mail.password=npuheyqdfqptptir
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.debug=true

logging.level.org.springframework=DEBUG
logging.level.fly.be.flyflix=DEBUG
